FROM python:3.8-alpine

ENV BACKEND_URL = http://0.0.0.0:4000

WORKDIR /app

ADD backend/requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

ADD backend /app

ENTRYPOINT ["python"]
CMD ["app.py"]
